### PR TITLE
Logging path now works when installed from source

### LINKED ISSUE #132: Install from source results in log file not found error
screen shot 2019-02-24 at 10 34 57 pm

### PR DESCRIPTION
**Pull request by nirtiac**
Fixes #132

### CODE REVIEW

**Comment by joemehltretter** [comment]
I'm still getting the error

**Comment by nirtiac** [comment]
@joemehltretter @rfratila acckkk ok. it's working for me across two environments, so not sure what's up if I can't replicate now. exact same error?

**Comment by rfratila** [comment]
@joemehltretter if you can give us a `pip freeze` output and some of the details of your environment we can troubleshoot it

**Comment by joemehltretter** [comment]
error

**Comment by joemehltretter** [comment]
pip_freeze

**Comment by joemehltretter** [comment]
My environment is a virtual environment with base python and I installed requirements via the requirements file and then did `python setup.py install`

**Comment by nirtiac** [comment]
@joemehltretter @rfratila now working everywhere for me.

**Comment by joemehltretter** [comment]
Working for me as well!

**Comment by rfratila** [comment]
looks good! please squash and merge @nirtiac

**Pull request merged**
